const listOfWords = [
  {
    base: "arise",
    past: "arose",
    pastParticiple: "arisen",
    ukrainian: "виникати",
    wrongAnswers: ["arised", "arising", "arisend"],
  },
  {
    base: "awake",
    past: "awoke",
    pastParticiple: "awoken",
    ukrainian: "прокидатися",
    wrongAnswers: ["awaked", "awakend", "awoking"],
  },
  {
    base: "be",
    past: "was/were",
    pastParticiple: "been",
    ukrainian: "бути",
    wrongAnswers: ["beed", "ben", "beinged"],
  },
  {
    base: "bear",
    past: "bore",
    pastParticiple: "born(e)",
    ukrainian: "народжувати",
    wrongAnswers: ["beared", "boren", "bearing"],
  },
  {
    base: "beat",
    past: "beat",
    pastParticiple: "beaten",
    ukrainian: "бити",
    wrongAnswers: ["beated", "beating", "beatened"],
  },
  {
    base: "become",
    past: "became",
    pastParticiple: "become",
    ukrainian: "ставати",
    wrongAnswers: ["becomed", "becoming", "becamend"],
  },
  {
    base: "begin",
    past: "began",
    pastParticiple: "begun",
    ukrainian: "починати",
    wrongAnswers: ["begined", "beginning", "begannd"],
  },
  {
    base: "bend",
    past: "bent",
    pastParticiple: "bent",
    ukrainian: "згинати",
    wrongAnswers: ["bended", "bending", "bentend"],
  },
  {
    base: "bet",
    past: "bet",
    pastParticiple: "bet",
    ukrainian: "ставити",
    wrongAnswers: ["betted", "betting", "beted"],
  },
  {
    base: "bind",
    past: "bound",
    pastParticiple: "bound",
    ukrainian: "зв'язувати",
    wrongAnswers: ["binded", "binding", "boundend"],
  },
  {
    base: "bite",
    past: "bit",
    pastParticiple: "bitten",
    ukrainian: "кусати",
    wrongAnswers: ["bited", "biting", "bittend"],
  },
  {
    base: "bleed",
    past: "bled",
    pastParticiple: "bled",
    ukrainian: "кровоточити",
    wrongAnswers: ["bleeded", "bleeding", "bledend"],
  },
  {
    base: "blow",
    past: "blew",
    pastParticiple: "blown",
    ukrainian: "дути",
    wrongAnswers: ["blowed", "blowing", "blownend"],
  },
  {
    base: "break",
    past: "broke",
    pastParticiple: "broken",
    ukrainian: "ламати",
    wrongAnswers: ["breaked", "breaking", "brokend"],
  },
  {
    base: "bring",
    past: "brought",
    pastParticiple: "brought",
    ukrainian: "приносити",
    wrongAnswers: ["bringed", "bringing", "broughtend"],
  },
  {
    base: "build",
    past: "built",
    pastParticiple: "built",
    ukrainian: "будувати",
    wrongAnswers: ["builded", "building", "builtend"],
  },
  {
    base: "buy",
    past: "bought",
    pastParticiple: "bought",
    ukrainian: "купувати",
    wrongAnswers: ["buyed", "buying", "boughtend"],
  },
  {
    base: "catch",
    past: "caught",
    pastParticiple: "caught",
    ukrainian: "ловити",
    wrongAnswers: ["catched", "catching", "caughtend"],
  },
  {
    base: "choose",
    past: "chose",
    pastParticiple: "chosen",
    ukrainian: "вибирати",
    wrongAnswers: ["choosed", "choosing", "chosend"],
  },
  {
    base: "come",
    past: "came",
    pastParticiple: "come",
    ukrainian: "приходити",
    wrongAnswers: ["comed", "coming", "camend"],
  },
  {
    base: "cost",
    past: "cost",
    pastParticiple: "cost",
    ukrainian: "коштувати",
    wrongAnswers: ["costed", "costing", "costend"],
  },
  {
    base: "cut",
    past: "cut",
    pastParticiple: "cut",
    ukrainian: "різати",
    wrongAnswers: ["cutted", "cutting", "cutend"],
  },
  {
    base: "deal",
    past: "dealt",
    pastParticiple: "dealt",
    ukrainian: "мати справу",
    wrongAnswers: ["dealed", "dealing", "dealtend"],
  },
  {
    base: "dig",
    past: "dug",
    pastParticiple: "dug",
    ukrainian: "копати",
    wrongAnswers: ["digged", "digging", "dugend"],
  },
  {
    base: "do",
    past: "did",
    pastParticiple: "done",
    ukrainian: "робити",
    wrongAnswers: ["doed", "doing", "didend"],
  },
  {
    base: "draw",
    past: "drew",
    pastParticiple: "drawn",
    ukrainian: "малювати",
    wrongAnswers: ["drawed", "drawing", "drewnd"],
  },
  {
    base: "dream",
    past: "dreamt/dreamed",
    pastParticiple: "dreamt/dreamed",
    ukrainian: "мріяти",
    wrongAnswers: ["dreamed", "dreaming", "dreamend"],
  },
  {
    base: "drink",
    past: "drank",
    pastParticiple: "drunk",
    ukrainian: "пити",
    wrongAnswers: ["drinked", "drinking", "drunkend"],
  },
  {
    base: "drive",
    past: "drove",
    pastParticiple: "driven",
    ukrainian: "водити",
    wrongAnswers: ["drived", "driving", "drovend"],
  },
  {
    base: "eat",
    past: "ate",
    pastParticiple: "eaten",
    ukrainian: "їсти",
    wrongAnswers: ["eated", "eating", "eatend"],
  },
  {
    base: "fall",
    past: "fell",
    pastParticiple: "fallen",
    ukrainian: "падати",
    wrongAnswers: ["falled", "falling", "fallend"],
  },
  {
    base: "feed",
    past: "fed",
    pastParticiple: "fed",
    ukrainian: "годувати",
    wrongAnswers: ["feeded", "feeding", "fedend"],
  },
  {
    base: "feel",
    past: "felt",
    pastParticiple: "felt",
    ukrainian: "відчувати",
    wrongAnswers: ["feeled", "feeling", "feltend"],
  },
  {
    base: "fight",
    past: "fought",
    pastParticiple: "fought",
    ukrainian: "битися",
    wrongAnswers: ["fighted", "fighting", "foughtend"],
  },
  {
    base: "find",
    past: "found",
    pastParticiple: "found",
    ukrainian: "знаходити",
    wrongAnswers: ["finded", "finding", "foundend"],
  },
  {
    base: "fly",
    past: "flew",
    pastParticiple: "flown",
    ukrainian: "літати",
    wrongAnswers: ["flyed", "flying", "flewend"],
  },
  {
    base: "forbid",
    past: "forbade",
    pastParticiple: "forbidden",
    ukrainian: "забороняти",
    wrongAnswers: ["forbided", "forbidding", "forbadend"],
  },
  {
    base: "forget",
    past: "forgot",
    pastParticiple: "forgotten",
    ukrainian: "забувати",
    wrongAnswers: ["forgeted", "forgetting", "forgotend"],
  },
  {
    base: "forgive",
    past: "forgave",
    pastParticiple: "forgiven",
    ukrainian: "прощати",
    wrongAnswers: ["forgived", "forgiving", "forgaveend"],
  },
  {
    base: "freeze",
    past: "froze",
    pastParticiple: "frozen",
    ukrainian: "заморожувати",
    wrongAnswers: ["freezed", "freezing", "frozeend"],
  },
  {
    base: "get",
    past: "got",
    pastParticiple: "got",
    ukrainian: "отримувати",
    wrongAnswers: ["getted", "getting", "gotend"],
  },
  {
    base: "give",
    past: "gave",
    pastParticiple: "given",
    ukrainian: "давати",
    wrongAnswers: ["gived", "giving", "gavend"],
  },
  {
    base: "go",
    past: "went",
    pastParticiple: "gone",
    ukrainian: "йти",
    wrongAnswers: ["goed", "going", "wentend"],
  },
  {
    base: "grind",
    past: "ground",
    pastParticiple: "ground",
    ukrainian: "молоти",
    wrongAnswers: ["grinded", "grinding", "groundend"],
  },
  {
    base: "grow",
    past: "grew",
    pastParticiple: "grown",
    ukrainian: "рости",
    wrongAnswers: ["growed", "growing", "grewend"],
  },
  {
    base: "hang",
    past: "hung",
    pastParticiple: "hung",
    ukrainian: "вішати",
    wrongAnswers: ["hanged", "hanging", "hungend"],
  },
  {
    base: "have",
    past: "had",
    pastParticiple: "had",
    ukrainian: "мати",
    wrongAnswers: ["haved", "having", "hadend"],
  },
  {
    base: "hear",
    past: "heard",
    pastParticiple: "heard",
    ukrainian: "чути",
    wrongAnswers: ["heared", "hearing", "heardend"],
  },
  {
    base: "hide",
    past: "hid",
    pastParticiple: "hidden",
    ukrainian: "ховати",
    wrongAnswers: ["hided", "hiding", "hidend"],
  },
  {
    base: "hit",
    past: "hit",
    pastParticiple: "hit",
    ukrainian: "вдаряти",
    wrongAnswers: ["hitted", "hitting", "hitend"],
  },
  {
    base: "hold",
    past: "held",
    pastParticiple: "held",
    ukrainian: "тримати",
    wrongAnswers: ["holded", "holding", "heldend"],
  },
  {
    base: "hurt",
    past: "hurt",
    pastParticiple: "hurt",
    ukrainian: "боліти",
    wrongAnswers: ["hurted", "hurting", "hurtend"],
  },
  {
    base: "keep",
    past: "kept",
    pastParticiple: "kept",
    ukrainian: "тримати",
    wrongAnswers: ["keeped", "keeping", "keptend"],
  },
  {
    base: "kneel",
    past: "knelt",
    pastParticiple: "knelt",
    ukrainian: "ставати на коліна",
    wrongAnswers: ["kneeled", "kneeling", "kneltend"],
  },
  {
    base: "know",
    past: "knew",
    pastParticiple: "known",
    ukrainian: "знати",
    wrongAnswers: ["knowed", "knowing", "knewend"],
  },
  {
    base: "lay",
    past: "laid",
    pastParticiple: "laid",
    ukrainian: "класти",
    wrongAnswers: ["layed", "laying", "laidend"],
  },
  {
    base: "lead",
    past: "led",
    pastParticiple: "led",
    ukrainian: "вести",
    wrongAnswers: ["leaded", "leading", "ledend"],
  },
  {
    base: "lean",
    past: "leant/leaned",
    pastParticiple: "leant/leaned",
    ukrainian: "нахилятися",
    wrongAnswers: ["leaned", "leaning", "leanend"],
  },
  {
    base: "learn",
    past: "learnt/learned",
    pastParticiple: "learnt/learned",
    ukrainian: "вчитися",
    wrongAnswers: ["learned", "learning", "learnend"],
  },
  {
    base: "leave",
    past: "left",
    pastParticiple: "left",
    ukrainian: "залишати",
    wrongAnswers: ["leaved", "leaving", "leftend"],
  },
  {
    base: "lend",
    past: "lent",
    pastParticiple: "lent",
    ukrainian: "позичати",
    wrongAnswers: ["lended", "lending", "lentend"],
  },
  {
    base: "lie (in bed)",
    past: "lay",
    pastParticiple: "lain",
    ukrainian: "лежати",
    wrongAnswers: ["lied", "lying", "layend"],
  },
  {
    base: "lie (to not tell the truth)",
    past: "lied",
    pastParticiple: "lied",
    ukrainian: "брехати",
    wrongAnswers: ["lieded", "lying", "liedend"],
  },
  {
    base: "light",
    past: "lit/lighted",
    pastParticiple: "lit/lighted",
    ukrainian: "запалювати",
    wrongAnswers: ["lighted", "lighting", "litend"],
  },
  {
    base: "lose",
    past: "lost",
    pastParticiple: "lost",
    ukrainian: "губити",
    wrongAnswers: ["loosed", "losing", "lostend"],
  },
  {
    base: "make",
    past: "made",
    pastParticiple: "made",
    ukrainian: "робити",
    wrongAnswers: ["maked", "making", "madeend"],
  },
  {
    base: "mean",
    past: "meant",
    pastParticiple: "meant",
    ukrainian: "мати на увазі",
    wrongAnswers: ["meaned", "meaning", "meantend"],
  },
  {
    base: "meet",
    past: "met",
    pastParticiple: "met",
    ukrainian: "зустрічати",
    wrongAnswers: ["meetend", "meeting", "metend"],
  },
  {
    base: "mow",
    past: "mowed",
    pastParticiple: "mown/mowed",
    ukrainian: "косити",
    wrongAnswers: ["mowedend", "mowing", "mowend"],
  },
  {
    base: "overtake",
    past: "overtook",
    pastParticiple: "overtaken",
    ukrainian: "обганяти",
    wrongAnswers: ["overtaked", "overtaking", "overtakend"],
  },
  {
    base: "pay",
    past: "paid",
    pastParticiple: "paid",
    ukrainian: "платити",
    wrongAnswers: ["payed", "paying", "paidend"],
  },
  {
    base: "put",
    past: "put",
    pastParticiple: "put",
    ukrainian: "класти",
    wrongAnswers: ["putted", "putting", "putend"],
  },
  {
    base: "read",
    past: "read",
    pastParticiple: "read",
    ukrainian: "читати",
    wrongAnswers: ["readed", "reading", "readend"],
  },
  {
    base: "ride",
    past: "rode",
    pastParticiple: "ridden",
    ukrainian: "їздити",
    wrongAnswers: ["rided", "riding", "rodeend"],
  },
  {
    base: "ring",
    past: "rang",
    pastParticiple: "rung",
    ukrainian: "дзвонити",
    wrongAnswers: ["ringed", "ringing", "rangend"],
  },
  {
    base: "rise",
    past: "rose",
    pastParticiple: "risen",
    ukrainian: "підніматися",
    wrongAnswers: ["rised", "rising", "roseend"],
  },
  {
    base: "run",
    past: "ran",
    pastParticiple: "run",
    ukrainian: "бігти",
    wrongAnswers: ["runned", "running", "ranend"],
  },
  {
    base: "say",
    past: "said",
    pastParticiple: "said",
    ukrainian: "казати",
    wrongAnswers: ["sayed", "saying", "saidend"],
  },
  {
    base: "see",
    past: "saw",
    pastParticiple: "seen",
    ukrainian: "бачити",
    wrongAnswers: ["seed", "seeing", "sawend"],
  },
  {
    base: "sell",
    past: "sold",
    pastParticiple: "sold",
    ukrainian: "продавати",
    wrongAnswers: ["selled", "selling", "soldend"],
  },
  {
    base: "send",
    past: "sent",
    pastParticiple: "sent",
    ukrainian: "відправляти",
    wrongAnswers: ["sended", "sending", "sentend"],
  },
  {
    base: "set",
    past: "set",
    pastParticiple: "set",
    ukrainian: "встановлювати",
    wrongAnswers: ["setted", "setting", "setend"],
  },
  {
    base: "sew",
    past: "sewed",
    pastParticiple: "sewn/sewed",
    ukrainian: "шити",
    wrongAnswers: ["sewedend", "sewing", "sewend"],
  },
  {
    base: "shake",
    past: "shook",
    pastParticiple: "shaken",
    ukrainian: "трусити",
    wrongAnswers: ["shaked", "shaking", "shookend"],
  },
  {
    base: "shed",
    past: "shed",
    pastParticiple: "shed",
    ukrainian: "позбавлятися",
    wrongAnswers: ["shedded", "shedding", "shedend"],
  },
  {
    base: "shine",
    past: "shone",
    pastParticiple: "shone",
    ukrainian: "світити",
    wrongAnswers: ["shined", "shining", "shoneend"],
  },
  {
    base: "shoot",
    past: "shot",
    pastParticiple: "shot",
    ukrainian: "стріляти",
    wrongAnswers: ["shooted", "shooting", "shotend"],
  },
  {
    base: "show",
    past: "showed",
    pastParticiple: "shown",
    ukrainian: "показувати",
    wrongAnswers: ["showedend", "showing", "showend"],
  },
  {
    base: "shrink",
    past: "shrank",
    pastParticiple: "shrunk",
    ukrainian: "зменшуватися",
    wrongAnswers: ["shrinked", "shrinking", "shrankend"],
  },
  {
    base: "shut",
    past: "shut",
    pastParticiple: "shut",
    ukrainian: "зачиняти",
    wrongAnswers: ["shutted", "shutting", "shutend"],
  },
  {
    base: "sing",
    past: "sang",
    pastParticiple: "sung",
    ukrainian: "співати",
    wrongAnswers: ["singed", "singing", "sangend"],
  },
  {
    base: "sink",
    past: "sank",
    pastParticiple: "sunk",
    ukrainian: "тонути",
    wrongAnswers: ["sinked", "sinking", "sankend"],
  },
  {
    base: "sit",
    past: "sat",
    pastParticiple: "sat",
    ukrainian: "сидіти",
    wrongAnswers: ["sitted", "sitting", "satend"],
  },
  {
    base: "sleep",
    past: "slept",
    pastParticiple: "slept",
    ukrainian: "спати",
    wrongAnswers: ["sleeped", "sleeping", "sleptend"],
  },
  {
    base: "slide",
    past: "slid",
    pastParticiple: "slid",
    ukrainian: "ковзати",
    wrongAnswers: ["slided", "sliding", "slidend"],
  },
  {
    base: "smell",
    past: "smelt",
    pastParticiple: "smelt",
    ukrainian: "пахнути",
    wrongAnswers: ["smelled", "smelling", "smeltend"],
  },
  {
    base: "speak",
    past: "spoke",
    pastParticiple: "spoken",
    ukrainian: "говорити",
    wrongAnswers: ["speaked", "speaking", "spokeend"],
  },
  {
    base: "spell",
    past: "spelt/spelled",
    pastParticiple: "spelt/spelled",
    ukrainian: "спеллювати",
    wrongAnswers: ["spelled", "spelling", "speltend"],
  },
  {
    base: "spend",
    past: "spent",
    pastParticiple: "spent",
    ukrainian: "витрачати",
    wrongAnswers: ["spended", "spending", "spentend"],
  },
  {
    base: "spill",
    past: "spilt/spilled",
    pastParticiple: "spilt/spilled",
    ukrainian: "розливати",
    wrongAnswers: ["spilled", "spilling", "spiltend"],
  },
  {
    base: "spin",
    past: "spun",
    pastParticiple: "spun",
    ukrainian: "крутити",
    wrongAnswers: ["spinned", "spinning", "spunend"],
  },
  {
    base: "spit",
    past: "spat",
    pastParticiple: "spat",
    ukrainian: "плювати",
    wrongAnswers: ["spited", "spitting", "spatend"],
  },
  {
    base: "spread",
    past: "spread",
    pastParticiple: "spread",
    ukrainian: "поширювати",
    wrongAnswers: ["spreaded", "spreading", "spreadend"],
  },
  {
    base: "stand",
    past: "stood",
    pastParticiple: "stood",
    ukrainian: "стояти",
    wrongAnswers: ["standed", "standing", "stoodend"],
  },
  {
    base: "steal",
    past: "stole",
    pastParticiple: "stolen",
    ukrainian: "красти",
    wrongAnswers: ["stealed", "stealing", "stoleend"],
  },
  {
    base: "stick",
    past: "stuck",
    pastParticiple: "stuck",
    ukrainian: "липнути",
    wrongAnswers: ["sticked", "sticking", "stuckend"],
  },
  {
    base: "sting",
    past: "stung",
    pastParticiple: "stung",
    ukrainian: "жалити",
    wrongAnswers: ["stunged", "stinging", "stungend"],
  },
  {
    base: "strike",
    past: "struck",
    pastParticiple: "struck",
    ukrainian: "вражати",
    wrongAnswers: ["striked", "striking", "struckend"],
  },
  {
    base: "swear",
    past: "swore",
    pastParticiple: "sworn",
    ukrainian: "клястися",
    wrongAnswers: ["swearend", "swearing", "sworend"],
  },
  {
    base: "sweep",
    past: "swept",
    pastParticiple: "swept",
    ukrainian: "підмітати",
    wrongAnswers: ["sweeped", "sweeping", "sweptend"],
  },
  {
    base: "swell",
    past: "swelled",
    pastParticiple: "swollen/swelled",
    ukrainian: "набухати",
    wrongAnswers: ["swelledend", "swelling", "swollend"],
  },
  {
    base: "swim",
    past: "swam",
    pastParticiple: "swum",
    ukrainian: "плавати",
    wrongAnswers: ["swimed", "swimming", "swamend"],
  },
  {
    base: "take",
    past: "took",
    pastParticiple: "taken",
    ukrainian: "брати",
    wrongAnswers: ["taked", "taking", "tookend"],
  },
  {
    base: "teach",
    past: "taught",
    pastParticiple: "taught",
    ukrainian: "вчити",
    wrongAnswers: ["teached", "teaching", "taughtend"],
  },
  {
    base: "tear",
    past: "tore",
    pastParticiple: "torn",
    ukrainian: "рвати",
    wrongAnswers: ["teared", "tearing", "tornend"],
  },
  {
    base: "tell",
    past: "told",
    pastParticiple: "told",
    ukrainian: "говорити",
    wrongAnswers: ["telled", "telling", "toldend"],
  },
  {
    base: "think",
    past: "thought",
    pastParticiple: "thought",
    ukrainian: "думати",
    wrongAnswers: ["thinked", "thinking", "thoughtend"],
  },
  {
    base: "throw",
    past: "threw",
    pastParticiple: "thrown",
    ukrainian: "кидати",
    wrongAnswers: ["throwed", "throwing", "threwend"],
  },
  {
    base: "understand",
    past: "understood",
    pastParticiple: "understood",
    ukrainian: "розуміти",
    wrongAnswers: ["understanded", "understanding", "understoodend"],
  },
  {
    base: "wake",
    past: "woke",
    pastParticiple: "woken",
    ukrainian: "прокидатися",
    wrongAnswers: ["waked", "waking", "wokeend"],
  },
  {
    base: "wear",
    past: "wore",
    pastParticiple: "worn",
    ukrainian: "носити",
    wrongAnswers: ["weared", "wearing", "woreend"],
  },
  {
    base: "weep",
    past: "wept",
    pastParticiple: "wept",
    ukrainian: "плакати",
    wrongAnswers: ["weeped", "weeping", "weptend"],
  },
  {
    base: "win",
    past: "won",
    pastParticiple: "won",
    ukrainian: "вигравати",
    wrongAnswers: ["winned", "winning", "wonend"],
  },
  {
    base: "write",
    past: "wrote",
    pastParticiple: "written",
    ukrainian: "писати",
    wrongAnswers: ["writed", "writing", "wroteend"],
  },
];

export default listOfWords;
